services:
  eleventy:
    container_name: 11ty
    image: node:lts-slim # zx needs bash
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
    restart: always

  app-admin:
    container_name: admin
    image: kennycallado/q-app-admin:latest
    build: .
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/http.d/default.conf
    ports:
      - 3000:80
    environment:
      ENVIRONMENT: "development"
      AUTH_URL: "http://auth:9000/auth"
      DATABASE_URL: "http://surrealdb:8000/sql"

  db:
    container_name: surrealdb
    image: kennycallado/q-api-store-demo:latest
    pull_policy: always
    ports:
      - 4000:8000
    command:
      - -A
      - --no-banner
      - --user=root
      - --pass=root
      - --bind=0.0.0.0:8000

  super:
    container_name: super
    image: kennycallado/q-api-super:latest
    pull_policy: always
    restart: always
    environment:
      DB_HOST: surrealdb:8000
    links:
      - db

  auth:
    container_name: auth
    image: kennycallado/q-api-auth:latest
    pull_policy: always
    restart: always
    ports:
      - 5000:9000
    environment:
      ROCKET_PORT: 9000
      ROCKET_DATABASES: '{store={host="surrealdb", port=8000, username="root", password="root"}}'
      ROCKET_SECRET_KEY: 'xdOXN1pEDSi3TYupqi7jOtXwaa3rOfClDPuW3HzMdkU='
    links:
      - db
