services:
  devcontainer:
    build:
      context: ../
      dockerfile: .devcontainer/Containerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    environment:
      PRELOAD_EXTENSIONS: arrterian.nix-env-selector 
    volumes:
      - ..:/workspace:cached
      - nix:/nix
    security_opt:
      - label:disable
    network_mode: bridge

volumes:
  nix:
